const worksData = [
  {
    id: 1,
    name: "Bio-Link",
    title: "Full-Stack Bio-Link Creator",
    thumbnail: "/assets/projects/bio-link.png",
    description:
      "Bio-Link is SASS application. It's build to create beautiful bio-link page, qr-code, link-visitor tracking and so on features it have.",
    features: null,
    app_type: "Full-Stack Application",
    technologies: ["Laravel", "MySQL", "Stripe", "Bootstrap 5"],
    live_url: "https://mylinks.ui-lib.com/",
  },
  {
    id: 2,
    name: "Biponi",
    title: "Full-Stack E-commerce Project",
    thumbnail: "/assets/projects/biponi.jpg",
    description:
      "Biponi is a Full-Stack E-commerce project. It have two dashboard one for general user and another one for super-admin. It is full customizable from super-admin dashboard",
    features: null,
    app_type: "Full-Stack Application",
    technologies: [
      "React",
      "NextJS",
      "Material-UI",
      "TypeScript",
      "Laravel",
      "MySQL",
    ],
    live_url: "",
  },
  {
    id: 3,
    name: "Bazar Pro",
    title: "E-commerce Template",
    thumbnail: "/assets/projects/bazar-nextjs.png",
    description:
      "Bazar Pro is an E-commerce Template that is sold on Material-UI official website",
    features: null,
    app_type: "Front-End Application",
    technologies: ["React", "NextJS", "Material-UI", "TypeScript"],
    live_url:
      "https://mui.com/store/previews/bazar-pro-react-ecommerce-template/",
  },
  {
    id: 4,
    name: "Trackem-GPS",
    title: "GPS Tracking Web App",
    thumbnail: "/assets/projects/trackem.png",
    description: "Trackem-GPS is a GPS Tracking App which is based on web",
    features: null,
    app_type: "Front-End Application",
    technologies: ["React", "NextJS", "Material-UI", "TypeScript"],
    live_url: "https://trackem.vercel.app/",
  },
  {
    id: 5,
    name: "Opacity Studio",
    title: "Portfolio Landing Page",
    thumbnail: "/assets/projects/opacity.png",
    description:
      "Opacity Studio is a landing page website. It's developed for a wonderful portfolio.",
    features: null,
    app_type: "Front-End Application",
    technologies: ["React", "NextJS", "Material-UI", "TypeScript"],
    live_url: "https://trackem.vercel.app/",
  },
  {
    id: 6,
    name: "Vendup-X",
    title: "E-commerce Dashboard Template",
    thumbnail: "/assets/projects/vendup.png",
    description:
      "Vendup-X is an Admin Dashboard Template for startup E-commerce business",
    features: null,
    app_type: "Front-End Application",
    technologies: ["React", "NextJS", "Material-UI", "TypeScript"],
    live_url: "https://vendup-seven.vercel.app/",
  },
  {
    id: 7,
    name: "GUll React",
    title: "Admin Dashboard Template",
    thumbnail: "/assets/projects/gull-react.png",
    description: "GUll is an Admin Dashboard Template",
    features: null,
    app_type: "Front-End Application",
    technologies: ["React", "Material-UI", "TypeScript"],
    live_url: "https://gull-mui-typescript.vercel.app/",
  },
  {
    id: 8,
    name: "Matx React Pro",
    title: "Admin Dashboard Template",
    thumbnail: "/assets/projects/matx-react-pro.png",
    description: "Matx React Pro is an Admin Dashboard Template",
    features: null,
    app_type: "Front-End Application",
    technologies: ["React", "Material-UI"],
    live_url: "http://matx-react.ui-lib.com/",
  },
  {
    id: 9,
    name: "Matx React",
    title: "Admin Dashboard Template Free",
    thumbnail: "/assets/projects/matx-react-free.png",
    description: "Matx React is a free version of Matx React Pro template",
    features: null,
    app_type: "Front-End Application",
    technologies: ["React", "Material-UI"],
    live_url: "https://matx-react-free.vercel.app/",
  },
];

export default worksData;
